Repository 0-Crew/WYB_Android, pull requests merged in 2022-04, with the labels that each got.

#7 [feat] 챌린지 오픈 하단 버튼 스타일 지정
  app/src/main/res/color/selector_full_width_button_background.xml
  app/src/main/res/color/selector_full_width_button_text.xml
  app/src/main/res/values/styles.xml
Labels: layout

#8 [feat] WYBPopupWindow 레이아웃 및 기능 구현
  app/build.gradle
  app/src/main/java/com/wyb/wyb_android/util/Extension.kt
  app/src/main/java/com/wyb/wyb_android/widget/WYBPopupWindowItemAdapter.kt
  app/src/main/res/drawable/selector_wyb_popup_window_item.xml
  app/src/main/res/drawable/thumb_wyb_popup_window_scrollbar.xml
  app/src/main/res/layout/item_wyb_popup_window.xml
  app/src/main/res/layout/item_wyb_popup_window_small.xml
  app/src/main/res/layout/view_wyb_popup_window.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: layout, feature

#9 [feat] 챌린지 오픈 관련 화면 및 ViewModel 생성
  app/src/main/java/com/wyb/wyb_android/ui/open/ChallengeOpenComfortFragment.kt
  app/src/main/java/com/wyb/wyb_android/ui/open/ChallengeOpenDiscomfortFragment.kt
  app/src/main/java/com/wyb/wyb_android/ui/open/ChallengeOpenStartDateFragment.kt
  app/src/main/java/com/wyb/wyb_android/ui/open/ChallengeOpenViewModel.kt
  app/src/main/res/layout/fragment_challenge_open_comfort.xml
  app/src/main/res/layout/fragment_challenge_open_discomfort.xml
  app/src/main/res/layout/fragment_challenge_open_start_date.xml
  app/src/main/res/navigation/challenge_open_nav_graph.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: feature

#10 [feat] WYBCompactTextButton CustomView 제작
  app/src/main/java/com/wyb/wyb_android/widget/WYBCompactTextButton.kt
  app/src/main/res/drawable/ic_calendar.xml
  app/src/main/res/drawable/ic_star_black.xml
  app/src/main/res/layout/view_wyb_compact_text_button.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/styles.xml
Labels: layout, feature

#11 Base ViewModelFragment 생성
  app/src/main/java/com/wyb/wyb_android/base/ViewModelFragment.kt
  app/src/main/java/com/wyb/wyb_android/ui/home/HomeFragment.kt
Labels: feature

#12 Show popup extension 제작
  app/src/main/java/com/wyb/wyb_android/util/ShowPopupWindow.kt
  app/src/main/res/drawable/shape_orange_stroke.xml
  app/src/main/res/values/integers.xml
Labels: feature

#13 [feat] 홈-친구 목록 adapter, data binding 연결
  app/src/main/java/com/wyb/wyb_android/data/model/OtherProfile.kt
  app/src/main/java/com/wyb/wyb_android/ui/home/HomeFragment.kt
  app/src/main/java/com/wyb/wyb_android/ui/home/HomeOtherProfileAdapter.kt
  app/src/main/res/layout/item_home_other_profile.xml
Labels: feature

#15 [layout] 챌린지 오픈 레이아웃 구현
  app/src/main/java/com/wyb/wyb_android/ui/open/ChallengeOpenComfortFragment.kt
  app/src/main/java/com/wyb/wyb_android/ui/open/ChallengeOpenDiscomfortFragment.kt
  app/src/main/java/com/wyb/wyb_android/ui/open/ChallengeOpenStartDateFragment.kt
  app/src/main/java/com/wyb/wyb_android/widget/WYBLabelEditText.kt
  app/src/main/res/color/selector_challenge_open_check_box_text.xml
  app/src/main/res/drawable-hdpi/ic_nav_bottle.png
  app/src/main/res/drawable-hdpi/ic_nav_bottle_washing.png
  app/src/main/res/drawable-mdpi/ic_nav_bottle.png
  app/src/main/res/drawable-mdpi/ic_nav_bottle_washing.png
  app/src/main/res/drawable-xhdpi/ic_nav_bottle.png
  app/src/main/res/drawable-xhdpi/ic_nav_bottle_washing.png
  app/src/main/res/drawable-xxhdpi/ic_nav_bottle.png
  app/src/main/res/drawable-xxhdpi/ic_nav_bottle_washing.png
  app/src/main/res/drawable-xxxhdpi/ic_nav_bottle.png
  app/src/main/res/drawable-xxxhdpi/ic_nav_bottle_washing.png
  app/src/main/res/drawable/ic_arrow_left.xml
  app/src/main/res/drawable/ic_x_24.xml
  app/src/main/res/drawable/progress_challenge_open.xml
  app/src/main/res/drawable/selector_challenge_open_check_box_background.xml
  app/src/main/res/drawable/shape_light_gray1_fill_light_gray2_stroke.xml
  app/src/main/res/layout/fragment_challenge_open_comfort.xml
  app/src/main/res/layout/fragment_challenge_open_discomfort.xml
  app/src/main/res/layout/fragment_challenge_open_start_date.xml
  app/src/main/res/layout/include_challenge_open_nav.xml
  app/src/main/res/layout/view_wyb_label_edit_text.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: layout
